redeploy_version = "v1"
project_id       = "<Your GCP Project ID>"
project_name     = "heritage-lens"
vpc_name         = "heritage-vpc"
region           = "us-central1"
zone             = "us-central1-a"
cidr_range       = "10.10.0.0/24"
vm_image         = "ubuntu-os-cloud/ubuntu-2204-lts"
mongo_uri        = "<mongodb+srv://user:password@heritage-lens.abcd123.mongodb.net/?retryWrites=true&w=majority&appName=heritage-lens>"
frontend_api_url = "{Your API URL}/api/explorer/search"
